
MIN_CAPTURE_FRAMES = 5
STATIC_GESTURE_MOTION_THRESHOLD = 0.012
CROP_W = 282
CROP_H = 342
CROP_X = 115
CROP_Y = 7
DATASET_VIDEOS_DIR="./señario1"
DATASET_NPY_DIR="./señario1_landmarks"
MAX_FRAMES=32
USE_FACE=True
USE_POSE=True
USE_HANDS=True
POSE_DIM = 33 * 3
HANDS_DIM = (21 * 3) * 2
FACE_DIM = 468 * 3
FRAME_FEATURES_DIM = POSE_DIM + HANDS_DIM + FACE_DIM